---
development:
  dialect: "sqlite3"
  database: {{envOr "DB_DEV_PATH" ".db\\development.sqlite"}}

test:
  dialect: "sqlite3"
  database: {{envOr "DB_TEST_PATH" ".db\\test.sqlite"}}

production:
  dialect: "sqlite3"
  database: {{envOr "DB_PROD_PATH" ".db\\production.sqlite"}}
